name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cd disassembler && cargo build --verbose && cd .. && cd emulator &&  cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
